### ISSUE TITLE
Failed to activate the carbon-copy package

### ISSUE THREAD

**Issue by achalbi** [rjain11/carbon-copy#2]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.22.1 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.12.6
**Thrown From**: [carbon-copy](https://github.com/rishabhjain2795/carbon-copy) package 1.0.2

### Stack Trace

Failed to activate the carbon-copy package

```
At Cannot read property 'command' of undefined

TypeError: Cannot read property 'command' of undefined
    at Object.activate (/packages/carbon-copy/lib/carbon-copy.coffee:3:23)
    at Package.module.exports.Package.activateNow (/private/var/folders/nx/f2vmrfp95kdg1sfgpdg3bdjr0000gn/T/AppTranslocation/B4BCB012-AFEC-4F78-AE1A-F9FCDE399905/d/Atom.app/Contents/Resources/app/src/package.js:253:25)
    at /private/var/folders/nx/f2vmrfp95kdg1sfgpdg3bdjr0000gn/T/AppTranslocation/B4BCB012-AFEC-4F78-AE1A-F9FCDE399905/d/Atom.app/Contents/Resources/app/src/package.js:225:38
    at Package.module.exports.Package.measure (/private/var/folders/nx/f2vmrfp95kdg1sfgpdg3bdjr0000gn/T/AppTranslocation/B4BCB012-AFEC-4F78-AE1A-F9FCDE399905/d/Atom.app/Contents/Resources/app/src/package.js:99:21)
    at /private/var/folders/nx/f2vmrfp95kdg1sfgpdg3bdjr0000gn/T/AppTranslocation/B4BCB012-AFEC-4F78-AE1A-F9FCDE399905/d/Atom.app/Contents/Resources/app/src/package.js:218:32
    at Package.module.exports.Package.activate (/private/var/folders/nx/f2vmrfp95kdg1sfgpdg3bdjr0000gn/T/AppTranslocation/B4BCB012-AFEC-4F78-AE1A-F9FCDE399905/d/Atom.app/Contents/Resources/app/src/package.js:215:40)
    at PackageManager.activatePackage (/private/var/folders/nx/f2vmrfp95kdg1sfgpdg3bdjr0000gn/T/AppTranslocation/B4BCB012-AFEC-4F78-AE1A-F9FCDE399905/d/Atom.app/Contents/Resources/app/src/package-manager.js:690:42)
    at config.transactAsync (/private/var/folders/nx/f2vmrfp95kdg1sfgpdg3bdjr0000gn/T/AppTranslocation/B4BCB012-AFEC-4F78-AE1A-F9FCDE399905/d/Atom.app/Contents/Resources/app/src/package-manager.js:665:36)
    at Config.module.exports.Config.transactAsync (/private/var/folders/nx/f2vmrfp95kdg1sfgpdg3bdjr0000gn/T/AppTranslocation/B4BCB012-AFEC-4F78-AE1A-F9FCDE399905/d/Atom.app/Contents/Resources/app/src/config.js:367:24)
    at PackageManager.activatePackages (/private/var/folders/nx/f2vmrfp95kdg1sfgpdg3bdjr0000gn/T/AppTranslocation/B4BCB012-AFEC-4F78-AE1A-F9FCDE399905/d/Atom.app/Contents/Resources/app/src/package-manager.js:663:23)
    at PackageManager.activate (/private/var/folders/nx/f2vmrfp95kdg1sfgpdg3bdjr0000gn/T/AppTranslocation/B4BCB012-AFEC-4F78-AE1A-F9FCDE399905/d/Atom.app/Contents/Resources/app/src/package-manager.js:646:50)
    at /private/var/folders/nx/f2vmrfp95kdg1sfgpdg3bdjr0000gn/T/AppTranslocation/B4BCB012-AFEC-4F78-AE1A-F9FCDE399905/d/Atom.app/Contents/Resources/app/src/atom-environment.js:854:36
```

### Commands

```
```

### Non-Core Packages

```
atom-copy-on-select 1.4.0 
atom-copy-with-line-numbers 0.1.0 
atom-elixir 0.2.3 
atom-elixir-formatter 0.2.1 
autoclose-html 0.23.0 
autocomplete-elixir 1.5.16 
babel-react-syntax 1.2.0 
build-elixir 0.7.0 
busy-signal 1.4.3 
carbon-copy 1.0.2 
compare-files 0.8.1 
copy-as-rtf 0.9.3 
copy-filename 1.0.1 
copy-highlighted 0.2.0 
copy-with-style 1.1.0 
copy-with-syntax 0.0.3 
elixir-cmd 0.2.9 
exunit 1.0.3 
flatwhite-syntax 0.8.1 
iex 0.10.0 
intentions 1.1.5 
language-babel 2.76.1 
language-dql 0.2.0 
language-elixir 0.20.3 
linter 2.2.0 
linter-elixir-credo 1.1.0 
linter-elixirc 1.7.0 
linter-ui-default 1.2.4 
nuclide 0.232.0 
nuclide-esformatter 0.3.1 
nuclide-format-js 0.0.41 
phoenix-elixir-snippets 0.4.0 
phoenix-toggle-test 0.2.0 
pure-syntax 0.3.0 
react-native-snippets 0.3.0 
sass-autocompile 0.13.3 
split-diff 1.3.0 
```

**Comment by europrimus** [comment]
it's the same for me and for #3 , #4 

I install the carbon-copy package from atom -> install package
but it never work. the package never get activated

**Atom**: 1.27.2 x64
**Electron**: 1.7.15
**OS**: Linux Mint
**Thrown From**: [carbon-copy](https://github.com/rishabhjain2795/carbon-copy) package 1.0.2


### Stack Trace

Failed to activate the carbon-copy package

```
At Cannot read property 'command' of undefined

TypeError: Cannot read property 'command' of undefined
    at Object.activate (/packages/carbon-copy/lib/carbon-copy.coffee:3:23)
    at Package.activateNow (/usr/share/atom/resources/app/src/package.js:230:33)
    at measure (/usr/share/atom/resources/app/src/package.js:206:33)
    at Package.measure (/usr/share/atom/resources/app/src/package.js:88:25)
    at activationPromise.Promise (/usr/share/atom/resources/app/src/package.js:200:20)
    at Promise (<anonymous>)
    at Package.activate (/usr/share/atom/resources/app/src/package.js:198:38)
    at PackageManager.activatePackage (/usr/share/atom/resources/app/src/package-manager.js:695:42)
    at config.transactAsync (/usr/share/atom/resources/app/src/package-manager.js:670:36)
    at Config.transactAsync (/usr/share/atom/resources/app/src/config.js:866:28)
    at PackageManager.activatePackages (/usr/share/atom/resources/app/src/package-manager.js:668:23)
    at PackageManager.activate (/usr/share/atom/resources/app/src/package-manager.js:647:50)
    at loadStatePromise.loadState.then (/usr/share/atom/resources/app/src/atom-environment.js:871:27)
    at <anonymous>
```

### Commands

```
```

### Non-Core Packages

```
carbon-copy 1.0.2 
color-picker 2.3.0 
git-log 0.4.1 
git-time-machine 2.1.0 
highlight-selected 0.13.1 
laravel-5-snippets 0.19.0 
minimap 4.29.8 
minimap-highlight-selected 4.6.1 
open-path 0.3.6 
reindent 1.5.0 
split-diff 1.5.2 
teletype 0.13.3 
tree-view-git-status 1.5.0 
```
